# Generated by Django 3.1.3 on 2020-11-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryPage', '0002_auto_20201114_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='plotpoint',
        ),
        migrations.RemoveField(
            model_name='choice_downvotes',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice_downvotes',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='choice_downvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice_edits',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice_edits',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='choice_edits',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice_upvotes',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice_upvotes',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='choice_upvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='downvotes',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='downvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='plot_point',
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Choice_Downvotes',
        ),
        migrations.DeleteModel(
            name='Choice_Edits',
        ),
        migrations.DeleteModel(
            name='Choice_Upvotes',
        ),
        migrations.DeleteModel(
            name='Downvotes',
        ),
        migrations.DeleteModel(
            name='Edits',
        ),
        migrations.DeleteModel(
            name='PlotPoint',
        ),
        migrations.DeleteModel(
            name='Upvotes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
