# Generated by Django 3.1.3 on 2020-12-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoryPage', '0003_auto_20201124_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('uv', models.IntegerField(default=0)),
                ('dv', models.IntegerField(default=0)),
                ('writtenby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlotPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pptext', models.CharField(max_length=1000)),
                ('uv', models.IntegerField(default=0)),
                ('dv', models.IntegerField(default=0)),
                ('isEnd', models.BooleanField(default=False)),
                ('writtenby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.BooleanField(default=True)),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Downvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.choice')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Edits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.BooleanField(default=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.choice')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Downvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.choice')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='StoryPage.plotpoint'),
        ),
        migrations.AddField(
            model_name='choice',
            name='plotpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.plotpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryPage.user')),
            ],
        ),
    ]
