# Generated by Django 3.1.3 on 2020-12-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryPage', '0004_auto_20201201_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotpoint',
            name='isEnd',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='writtenby',
            field=models.CharField(max_length=20),
        ),
    ]
