# Generated by Django 3.1.3 on 2020-12-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryPage', '0005_auto_20201201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='destination',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='StoryPage.plotpoint'),
        ),
        migrations.AlterField(
            model_name='choice_downvotes',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='choice_edits',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='choice_upvotes',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='downvotes',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='edits',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='isEnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
